name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up SSH connection to AWS server
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

    - name: Run Docker commands on AWS server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@52.47.147.84 << 'EOF'
        cd nuitee-chatbot
        sudo git pull origin
        docker stop $(docker ps -aq) || true
        docker rm $(docker ps -aq) || true
        docker rmi $(docker images -q) || true
        docker build -t server-image -f ./server/server.dockerfile ./server
        docker build -t client-image -f ./client/client.dockerfile ./client
        docker run -d -p 8080:8080 --name server server-image
        docker run -d -p 5173:5173 --name client client-image
        EOF
